import { createHostelReservationAction, updateHostelReservationStatusAction } from "@/app/actions";
import { all } from "@/lib/db";
import { dateLabel, money, today } from "@/lib/format";
import { permissionScopeSql, requirePortfolioPermission } from "@/lib/permissions";
import PageHeader from "@/components/PageHeader";
import OpenModalButton from "@/components/OpenModalButton";
import ModalForm from "@/components/ModalForm";
import ConfirmAction from "@/components/ConfirmAction";
import ActionButton from "@/components/ActionButton";
import Flash from "@/components/Flash";
import Badge from "@/components/Badge";
import Empty from "@/components/Empty";
import Icon from "@/components/Icon";

export const metadata = { title: "Hostel reservations" };
const nights = (arrival, departure) => Math.max(1, Math.round((new Date(`${departure}T00:00:00Z`) - new Date(`${arrival}T00:00:00Z`)) / 86400000));

function TransitionConfirmation({ item, status, label, title, consequence, triggerClassName = "text-button danger" }) {
  return <ConfirmAction action={updateHostelReservationStatusAction} id={`reservation-${status}-${item.id}`} triggerLabel={label} triggerClassName={triggerClassName} title={title} description={`${item.reference} · ${item.guest_name} · ${item.property_name}`} submitLabel={label} pendingLabel="Updating…"><div className="modal-body"><input type="hidden" name="reservationId" value={item.id}/><input type="hidden" name="status" value={status}/><div className="confirm-consequence">{consequence}</div></div></ConfirmAction>;
}

export default async function ReservationsPage({ searchParams }) {
  const user = await requirePortfolioPermission("reservations.manage");
  const scope = permissionScopeSql(user, "reservations.manage", "p");
  const query = await searchParams;
  const properties = all(`SELECT p.* FROM properties p WHERE ${scope.clause} AND p.module_id='hostel' AND p.status='active' ORDER BY p.name`, scope.params);
  const propertyIds = properties.map((property) => Number(property.id));
  const reservations = propertyIds.length ? all(`SELECT hr.*,p.name property_name,p.currency,u.name unit_name,rs.code space_code,creator.name creator_name FROM hostel_reservations hr JOIN properties p ON p.id=hr.property_id LEFT JOIN units u ON u.id=hr.unit_id LEFT JOIN rentable_spaces rs ON rs.id=hr.space_id LEFT JOIN users creator ON creator.id=hr.created_by WHERE hr.property_id IN (${propertyIds.map(() => "?").join(",")}) ORDER BY CASE hr.status WHEN 'checked_in' THEN 0 WHEN 'reserved' THEN 1 ELSE 2 END,hr.arrival_date,hr.id DESC LIMIT 500`, propertyIds) : [];
  const units = propertyIds.length ? all(`SELECT u.id,u.name,u.property_id,p.name property_name FROM units u JOIN properties p ON p.id=u.property_id WHERE u.property_id IN (${propertyIds.map(() => "?").join(",")}) AND u.status NOT IN ('maintenance','inactive') ORDER BY p.name,u.name`, propertyIds) : [];
  const spaces = propertyIds.length ? all(`SELECT rs.id,rs.code,rs.property_id,rs.unit_id,rs.monthly_rate,p.name property_name,u.name unit_name FROM rentable_spaces rs JOIN properties p ON p.id=rs.property_id JOIN units u ON u.id=rs.unit_id WHERE rs.property_id IN (${propertyIds.map(() => "?").join(",")}) AND rs.status!='inactive' AND u.status NOT IN ('maintenance','inactive') ORDER BY p.name,u.name,rs.code`, propertyIds) : [];
  const arrivals = reservations.filter((item) => item.status === "reserved" && item.arrival_date === today()).length;
  const departures = reservations.filter((item) => item.status === "checked_in" && item.departure_date === today()).length;
  const inHouse = reservations.filter((item) => item.status === "checked_in").length;
  const future = reservations.filter((item) => item.status === "reserved" && item.arrival_date > today()).length;

  return <>
    <Flash searchParams={query}/>
    <PageHeader eyebrow="Hostel front desk" title="Reservations, arrivals & departures" description="Manage date-bound bed reservations with overlap protection, controlled check-in transitions, no-show handling, and automatic housekeeping turnover at checkout." actions={properties.length > 0 ? <OpenModalButton target="reservation-create" icon="plus">New reservation</OpenModalButton> : null}/>
    <section className="metric-grid module-metric-grid"><article className={`metric-card${arrivals ? " risk" : ""}`}><span>Arriving today</span><strong>{arrivals}</strong><small>Reserved and awaiting check-in</small></article><article className={`metric-card${departures ? " risk" : ""}`}><span>Departing today</span><strong>{departures}</strong><small>Checked-in stays due out</small></article><article className="metric-card"><span>Currently in house</span><strong>{inHouse}</strong><small>Checked-in reservations</small></article><article className="metric-card"><span>Future reservations</span><strong>{future}</strong><small>Upcoming confirmed inventory</small></article></section>

    {reservations.length ? <section className="reservation-board">{["checked_in", "reserved", "checked_out", "cancelled", "no_show"].map((status) => <div className="reservation-column" key={status}><div className="reservation-column-head"><span>{status.replaceAll("_", " ")}</span><strong>{reservations.filter((item) => item.status === status).length}</strong></div><div className="reservation-list">{reservations.filter((item) => item.status === status).map((item) => { const total=Number(item.nightly_rate)*nights(item.arrival_date,item.departure_date)+Number(item.tax_amount); return <article className="reservation-card" key={item.id}><div className="reservation-card-top"><Badge tone={item.status}>{item.status.replaceAll("_", " ")}</Badge><small>{item.reference}</small></div><h2>{item.guest_name}</h2><p>{item.property_name} · {item.unit_name || "Unassigned room"}{item.space_code ? ` · ${item.space_code}` : ""}</p><div className="reservation-dates"><span><small>Arrival</small><strong>{dateLabel(item.arrival_date)}</strong></span><Icon name="arrow" size={15}/><span><small>Departure</small><strong>{dateLabel(item.departure_date)}</strong></span></div><div className="reservation-meta"><span>{nights(item.arrival_date,item.departure_date)} night(s)</span><span>{money(total,item.currency)}</span><span>{item.source}</span></div><div className="reservation-actions">{item.status === "reserved" && <><form action={updateHostelReservationStatusAction}><input type="hidden" name="reservationId" value={item.id}/><input type="hidden" name="status" value="checked_in"/><ActionButton className="button primary small" pendingLabel="Checking in…">Check in</ActionButton></form><TransitionConfirmation item={item} status="no_show" label="Mark no-show" title="Mark this guest as a no-show?" consequence="This releases the reservation from the active arrival queue and records the no-show transition in the audit history."/><TransitionConfirmation item={item} status="cancelled" label="Cancel reservation" title="Cancel this reservation?" consequence="This removes the reservation from active inventory. The original reservation record remains in history."/></>}{item.status === "checked_in" && <TransitionConfirmation item={item} status="checked_out" label="Check out" title="Check out this guest?" triggerClassName="button primary small" consequence="Checkout ends the active stay and automatically creates the associated housekeeping turnover task."/>}</div></article>; })}</div></div>)}</section> : <Empty icon="hostel" title="No hostel reservations" text={properties.length ? "Create the first direct, walk-in, phone, group, or channel reservation." : "No permitted active Hostel property is available."/>} 

    {properties.length > 0 && <form action={createHostelReservationAction}><ModalForm id="reservation-create" title="Create hostel reservation" description="The selected bed is checked for every overlapping active reservation before insertion." submitLabel="Reserve stay" pendingLabel="Reserving…"><div className="modal-body"><label><span>Hostel</span><select name="propertyId" required>{properties.map((property) => <option value={property.id} key={property.id}>{property.name}</option>)}</select></label><div className="field-grid two"><label><span>Room / dorm</span><select name="unitId"><option value="">Assign later</option>{units.map((unit) => <option value={unit.id} key={unit.id}>{unit.property_name} · {unit.name}</option>)}</select></label><label><span>Bed</span><select name="spaceId"><option value="">Assign later</option>{spaces.map((space) => <option value={space.id} key={space.id}>{space.property_name} · {space.unit_name} · {space.code}</option>)}</select></label></div><div className="field-grid two"><label><span>Guest name</span><input name="guestName" required/></label><label><span>Adults</span><input type="number" min="1" name="adults" defaultValue="1"/></label></div><div className="field-grid two"><label><span>Email</span><input type="email" name="guestEmail"/></label><label><span>Phone</span><input name="guestPhone" inputMode="tel"/></label></div><div className="field-grid two"><label><span>Arrival</span><input type="date" name="arrivalDate" defaultValue={today()} required/></label><label><span>Departure</span><input type="date" name="departureDate" required/></label></div><div className="field-grid three"><label><span>Nightly rate</span><input type="number" min="0" step="0.01" name="nightlyRate" defaultValue="0"/></label><label><span>Tax amount</span><input type="number" min="0" step="0.01" name="taxAmount" defaultValue="0"/></label><label><span>Source</span><select name="source"><option value="direct">Direct</option><option value="walk_in">Walk-in</option><option value="phone">Phone</option><option value="group">Group</option><option value="channel">External channel</option></select></label></div><label><span>Identity / passport reference</span><input name="identityReference"/></label><label><span>Notes</span><textarea name="notes" rows="3"/></label></div></ModalForm></form>}
  </>;
}
