import Link from "next/link";
import { acknowledgeInspectionAction } from "@/app/actions";
import { requireTenant } from "@/lib/tenant-auth";
import { portalLeaseData } from "@/lib/portal-data";
import { portalHandoverData } from "@/lib/handover-data";
import { portalCommercialData, portalSpaceData } from "@/lib/module-data";
import { moduleById } from "@/lib/modules/catalog";
import { dateLabel, dateTimeLabel, money } from "@/lib/format";
import Badge from "@/components/Badge";
import Icon from "@/components/Icon";
import Flash from "@/components/Flash";
import OpenModalButton from "@/components/OpenModalButton";
import ModalForm from "@/components/ModalForm";
import ModuleBadge from "@/components/ModuleBadge";

export const metadata = { title: "My agreement & handover" };

function depositSign(type) { return ["received", "credit"].includes(type) ? 1 : -1; }
function conditionTone(condition) { if (["excellent", "good"].includes(condition)) return "paid"; if (["damaged", "missing"].includes(condition)) return "overdue"; return "inactive"; }

export default async function PortalLeasePage({ searchParams }) {
  const tenant = await requireTenant();
  const module = moduleById(tenant.module_id);
  const data = portalLeaseData(tenant.tenant_id);
  const handover = portalHandoverData(tenant.tenant_id);
  const spaces = portalSpaceData(tenant.tenant_id);
  const commercial = portalCommercialData(tenant.tenant_id);
  const query = await searchParams;
  const active = data.leases.find((lease) => lease.status === "active");
  const title = module.id === "commercial" ? "My premises, documents, and handover" : "My home, documents, and handover";
  return <>
    <Flash searchParams={query}/>
    <header className="portal-page-head"><div><span className="eyebrow">{module.terminology.agreement} record</span><h1>{title}</h1><p>Terms, module-specific allocations, deposit movements, condition reports, files, and access records connected to your profile.</p></div><ModuleBadge moduleId={module.id}/></header>

    {active ? <section className="portal-lease-hero">
      <div className="portal-lease-identity"><span className="portal-detail-icon large"><Icon name={module.id === "commercial" ? "commercial" : "home"} size={26}/></span><div><span className="eyebrow">Active {module.terminology.agreement.toLowerCase()}</span><h2>{active.property_name} · {active.unit_name}</h2><p>{active.property_address}{active.city ? `, ${active.city}` : ""}{active.country ? `, ${active.country}` : ""}</p></div><Badge tone="active">Active</Badge></div>
      <div className="portal-lease-terms"><span><small>Reference</small><strong>{active.reference}</strong></span><span><small>Monthly rent</small><strong>{money(active.monthly_rent, active.currency)}</strong></span><span><small>Billing day</small><strong>Day {active.billing_day}</strong></span><span><small>Started</small><strong>{dateLabel(active.start_date)}</strong></span><span><small>Scheduled end</small><strong>{active.end_date ? dateLabel(active.end_date) : "Open-ended"}</strong></span><span><small>{module.terminology.occupant}s</small><strong>{active.resident_names || tenant.full_name}</strong></span></div>
      {active.notes && <div className="portal-lease-note"><span>Agreement note</span><p>{active.notes}</p></div>}
    </section> : <section className="portal-card portal-empty-state"><Icon name={module.id === "commercial" ? "commercial" : "home"} size={30}/><strong>No active {module.terminology.agreement.toLowerCase()}</strong><p>Your historical records remain available.</p></section>}

    {spaces.length > 0 && <section className="portal-card"><div className="portal-card-head"><div><span className="eyebrow">Assigned inventory</span><h2>My bed or space</h2></div></div><div className="portal-space-list">{spaces.map((space) => <article key={space.id}><span className="portal-service-icon"><Icon name="spaces" size={20}/></span><span><strong>{space.code}</strong><small>{space.property_name} · {space.unit_name} · {space.space_type}</small><p>{space.gender_policy === "any" ? "No restricted occupancy policy" : `${space.gender_policy} occupancy policy`}</p></span><span><strong>{space.status === "active" ? "Currently allocated" : "Historical allocation"}</strong><small>{dateLabel(space.start_date)} to {space.end_date ? dateLabel(space.end_date) : "present"}</small></span><Badge tone={space.status}>{space.status}</Badge></article>)}</div></section>}

    {commercial.length > 0 && <section className="portal-card"><div className="portal-card-head"><div><span className="eyebrow">Commercial terms</span><h2>Business profile</h2></div></div><div className="portal-commercial-grid">{commercial.map((profile) => <article key={profile.id}><div><span className="eyebrow">{profile.lease_reference}</span><h3>{profile.business_name}</h3><p>{profile.business_activity || "Business activity not recorded"}</p></div><div className="portal-detail-grid"><span><small>Registration</small><strong>{profile.registration_number || "—"}</strong></span><span><small>Tax number</small><strong>{profile.tax_number || "—"}</strong></span><span><small>Monthly CAM</small><strong>{money(profile.common_area_charge, profile.currency)}</strong></span><span><small>Escalation</small><strong>{profile.escalation_percent}%{profile.escalation_date ? ` · ${dateLabel(profile.escalation_date)}` : ""}</strong></span><span><small>Fit-out end</small><strong>{profile.fitout_end_date ? dateLabel(profile.fitout_end_date) : "—"}</strong></span><span><small>Notice period</small><strong>{profile.notice_period_days} days</strong></span></div>{profile.notes && <p className="portal-commercial-note">{profile.notes}</p>}</article>)}</div></section>}

    {active && <section className="portal-deposit-summary"><article><span>Deposit required</span><strong>{money(active.deposit, active.currency)}</strong><small>Contractual amount</small></article><article><span>Deposit currently held</span><strong>{money(active.deposit_held, active.currency)}</strong><small>Received and credits minus refunds and debits</small></article><article><span>Difference</span><strong>{money(Number(active.deposit) - Number(active.deposit_held), active.currency)}</strong><small>{Number(active.deposit_held) >= Number(active.deposit) ? "Requirement covered" : "Remaining against requirement"}</small></article></section>}

    <section className="portal-card"><div className="portal-card-head"><div><span className="eyebrow">Shared records</span><h2>Documents</h2></div><Badge tone={handover.documents.length ? "active" : "inactive"}>{handover.documents.length}</Badge></div>{handover.documents.length ? <div className="portal-document-grid">{handover.documents.map((item) => <a href={`/portal/lease-documents/${item.id}`} target="_blank" rel="noreferrer" key={item.id}><span className="portal-activity-icon"><Icon name="document" size={18}/></span><span><strong>{item.title}</strong><small>{item.document_type.replaceAll("_", " ")} · {item.property_name} · {dateLabel(item.created_at.slice(0, 10))}</small></span><Icon name="arrow" size={16}/></a>)}</div> : <div className="portal-empty-state compact"><Icon name="document" size={26}/><strong>No tenant-visible documents</strong><p>Agreements, notices, inventories, and handover files shared by the property team will appear here.</p></div>}</section>

    <section className="portal-card"><div className="portal-card-head"><div><span className="eyebrow">Condition evidence</span><h2>Inspections</h2></div></div>{handover.inspections.length ? <div className="portal-inspection-list">{handover.inspections.map((inspection) => {const items=handover.itemsByInspection[Number(inspection.id)]||[];return <article className="portal-inspection-card" key={inspection.id}><div className="portal-inspection-head"><span><strong>{inspection.reference}</strong><small>{inspection.inspection_type.replaceAll("_", " ")} · {inspection.property_name} · {inspection.unit_name} · {dateLabel(inspection.scheduled_for)}</small></span><Badge tone={inspection.status}>{inspection.status}</Badge></div>{inspection.summary&&<p>{inspection.summary}</p>}{(inspection.electricity_meter||inspection.water_meter||inspection.gas_meter)&&<div className="portal-meter-grid"><span><small>Electricity</small><strong>{inspection.electricity_meter||"—"}</strong></span><span><small>Water</small><strong>{inspection.water_meter||"—"}</strong></span><span><small>Gas</small><strong>{inspection.gas_meter||"—"}</strong></span></div>}<div className="portal-condition-list">{items.map((item)=><div key={item.id}><span><strong>{item.area} · {item.item_name}</strong><small>{item.notes||"No condition note"}</small></span><span><Badge tone={conditionTone(item.condition)}>{item.condition.replaceAll("_"," ")}</Badge>{Number(item.charge_amount)>0&&<small>{money(item.charge_amount,inspection.currency)} assessed</small>}</span></div>)}</div><div className="portal-inspection-foot"><span>{inspection.acknowledged_at?`Acknowledged ${dateTimeLabel(inspection.acknowledged_at)}`:"Awaiting your acknowledgement"}</span>{!inspection.acknowledged_at&&["shared","acknowledged","completed"].includes(inspection.status)&&<OpenModalButton target={`ack-inspection-${inspection.id}`} className="button secondary">Review and acknowledge</OpenModalButton>}</div></article>})}</div> : <div className="portal-empty-state compact"><Icon name="inspection" size={26}/><strong>No shared condition reports</strong><p>Move-in, periodic, or move-out reports become visible after the property team shares them.</p></div>}</section>

    <section className="portal-card"><div className="portal-card-head"><div><span className="eyebrow">Physical access</span><h2>Keys and access items</h2></div></div>{handover.keys.length ? <div className="portal-key-list">{handover.keys.map((item)=><article key={item.id}><span className="portal-activity-icon"><Icon name="key" size={18}/></span><span><strong>{item.key_type} · {item.quantity}</strong><small>{item.action} · {item.property_name} · {item.unit_name} · {dateLabel(item.transacted_at)}{item.attributed_tenant?` · ${item.attributed_tenant}`:""}</small></span><Badge tone={["issued","replaced"].includes(item.action)?"active":"inactive"}>{item.action}</Badge></article>)}</div> : <div className="portal-empty-state compact"><strong>No key transactions recorded</strong></div>}</section>

    <section className="portal-card"><div className="portal-card-head"><div><span className="eyebrow">Refundable ledger</span><h2>Deposit transactions</h2></div></div>{data.deposits.length ? <div className="portal-deposit-list">{data.deposits.map((item)=><Link href={`/portal/deposit-receipts/${item.id}`} key={item.id}><span className={`portal-activity-icon ${depositSign(item.transaction_type)>0?"positive":"negative"}`}><Icon name="deposit" size={18}/></span><span><strong>{item.reference}</strong><small>{item.transaction_type.replaceAll("_"," ")} · {item.property_name} · {item.unit_name} · {dateLabel(item.transacted_at)}{item.attributed_tenant_name?` · ${item.attributed_tenant_name}`:" · lease-level"}</small></span><strong>{depositSign(item.transaction_type)>0?"+":"−"}{money(item.amount,item.currency)}</strong><Icon name="arrow" size={16}/></Link>)}</div> : <div className="portal-empty-state compact"><strong>No deposit transactions recorded</strong></div>}</section>

    <section className="portal-card"><div className="portal-card-head"><div><span className="eyebrow">History</span><h2>All linked agreements</h2></div></div>{data.leases.length ? <div className="portal-lease-history">{data.leases.map((lease)=><article key={lease.id}><span><strong>{lease.property_name} · {lease.unit_name}</strong><small>{lease.reference} · {dateLabel(lease.start_date)} to {lease.end_date?dateLabel(lease.end_date):"present"}</small></span><span><strong>{money(lease.monthly_rent,lease.currency)}/month</strong><small>Deposit held {money(lease.deposit_held,lease.currency)}</small></span><Badge tone={lease.status}>{lease.status}</Badge></article>)}</div> : <div className="portal-empty-state compact"><strong>No agreement history</strong></div>}</section>

    {handover.inspections.filter((item)=>!item.acknowledged_at&&["shared","acknowledged","completed"].includes(item.status)).map((inspection)=><form action={acknowledgeInspectionAction} key={`ack-${inspection.id}`}><ModalForm id={`ack-inspection-${inspection.id}`} title={`Acknowledge ${inspection.reference}`} description="This records that you received and reviewed the condition report. It is not a waiver, admission, or legal signature." submitLabel="Acknowledge receipt"><div className="modal-body"><input type="hidden" name="inspectionId" value={inspection.id}/><div className="summary-box"><span>Condition report</span><strong>{inspection.inspection_type.replaceAll("_"," ")} · {dateLabel(inspection.scheduled_for)}</strong><small>{inspection.item_count} item(s) · {money(inspection.assessed_charge,inspection.currency)} assessed</small></div><label><span>Your note (optional)</span><textarea name="tenantNote" rows="4" placeholder="Record any disagreement, clarification, existing damage, or follow-up requested"/></label><div className="policy-warning">Acknowledgement confirms receipt and review only. Your note is preserved with the report.</div></div></ModalForm></form>)}
  </>;
}
