import { billServiceSubscriptionAction, createServiceAction, endServiceSubscriptionAction, subscribeServiceAction, updateServiceAction } from "@/app/actions";
import { propertyScopeSql, requireUser } from "@/lib/auth";
import { all } from "@/lib/db";
import { money, dateLabel, today } from "@/lib/format";
import { supportsCapability } from "@/lib/modules/catalog";
import PageHeader from "@/components/PageHeader";
import OpenModalButton from "@/components/OpenModalButton";
import ModalForm from "@/components/ModalForm";
import Flash from "@/components/Flash";
import Badge from "@/components/Badge";
import Empty from "@/components/Empty";
import ModuleBadge from "@/components/ModuleBadge";

export const metadata = { title: "Services & add-ons" };

export default async function ServicesPage({ searchParams }) {
  const user = await requireUser();
  const scope = propertyScopeSql(user, "p");
  const period = today().slice(0, 7);
  const allProperties = all(`SELECT p.* FROM properties p WHERE ${scope.clause} AND p.status='active' ORDER BY p.name`, scope.params);
  const properties = allProperties.filter((property) => supportsCapability(property.module_id, "servicePlans"));
  const propertyIds = properties.map((property) => Number(property.id));
  const services = propertyIds.length ? all(`SELECT sc.*,p.name property_name,p.currency,p.module_id,(SELECT COUNT(*) FROM lease_services ls WHERE ls.service_id=sc.id AND ls.status='active') active_subscriptions FROM service_catalog sc JOIN properties p ON p.id=sc.property_id WHERE sc.property_id IN (${propertyIds.map(() => "?").join(",")}) ORDER BY p.name,sc.active DESC,sc.name`, propertyIds) : [];
  const subscriptions = propertyIds.length ? all(
    `SELECT ls.*,sc.name service_name,sc.billing_frequency,sc.amount service_amount,p.name property_name,p.currency,p.module_id,l.reference lease_reference,u.name unit_name,t.full_name tenant_name,
      sbr.invoice_id current_invoice_id,i.number current_invoice_number
     FROM lease_services ls JOIN service_catalog sc ON sc.id=ls.service_id JOIN properties p ON p.id=ls.property_id
     JOIN leases l ON l.id=ls.lease_id JOIN units u ON u.id=l.unit_id LEFT JOIN tenants t ON t.id=ls.tenant_id
     LEFT JOIN service_billing_runs sbr ON sbr.subscription_id=ls.id AND sbr.period=CASE WHEN sc.billing_frequency='one_time' THEN 'one-time' ELSE ? END
     LEFT JOIN invoices i ON i.id=sbr.invoice_id
     WHERE ls.property_id IN (${propertyIds.map(() => "?").join(",")}) ORDER BY CASE ls.status WHEN 'active' THEN 0 ELSE 1 END,p.name,sc.name`,
    [period, ...propertyIds]
  ) : [];
  const leases = propertyIds.length ? all(`SELECT l.id,l.reference,l.property_id,p.name property_name,u.name unit_name FROM leases l JOIN properties p ON p.id=l.property_id JOIN units u ON u.id=l.unit_id WHERE l.property_id IN (${propertyIds.map(() => "?").join(",")}) AND l.status='active' ORDER BY p.name,u.name`, propertyIds) : [];
  const tenants = leases.length ? all(`SELECT lt.lease_id,t.id,t.full_name FROM lease_tenants lt JOIN tenants t ON t.id=lt.tenant_id WHERE lt.lease_id IN (${leases.map(() => "?").join(",")}) ORDER BY t.full_name`, leases.map((lease) => Number(lease.id))) : [];
  const query = await searchParams;
  const canConfigure = user.role !== "staff";
  const activeSubscriptions = subscriptions.filter((item) => item.status === "active");
  const billable = activeSubscriptions.filter((item) => item.billing_frequency !== "included");
  const billed = billable.filter((item) => item.current_invoice_id).length;

  return <>
    <Flash searchParams={query}/>
    <PageHeader eyebrow="Module services" title="Services & add-ons" description="Manage meals, laundry, Wi-Fi, housekeeping, lockers, parking, CAM, and other module-relevant entitlements with repeat-safe billing." actions={<>{canConfigure && properties.length ? <OpenModalButton target="service-create">New service</OpenModalButton> : null}{services.some((service) => service.active) && leases.length ? <OpenModalButton target="service-assign" className="button secondary">Assign service</OpenModalButton> : null}</>}/>
    <section className="metric-grid module-metric-grid"><article className="metric-card"><span>Active catalogue items</span><strong>{services.filter((item) => item.active).length}</strong><small>Across {properties.length} compatible properties</small></article><article className="metric-card"><span>Active subscriptions</span><strong>{activeSubscriptions.length}</strong><small>Lease or resident level</small></article><article className="metric-card"><span>Billed this period</span><strong>{billed}</strong><small>{period} idempotent runs</small></article><article className={`metric-card${billable.length - billed ? " risk" : ""}`}><span>Awaiting billing</span><strong>{Math.max(0, billable.length - billed)}</strong><small>Included services excluded</small></article></section>

    <section className="panel module-section"><div className="panel-head"><div><span className="eyebrow">Available entitlements</span><h2>Service catalogue</h2></div>{canConfigure && <OpenModalButton target="service-create" className="button secondary">Add service</OpenModalButton>}</div>{services.length ? <div className="table-wrap"><table><thead><tr><th>Service</th><th>Property</th><th>Frequency</th><th>Default charge</th><th>Subscriptions</th><th>Status</th><th></th></tr></thead><tbody>{services.map((service) => <tr key={service.id}><td><strong>{service.name}</strong><small>{service.category} · {service.description || "No description"}</small></td><td><ModuleBadge moduleId={service.module_id} compact/><small>{service.property_name}</small></td><td>{service.billing_frequency.replaceAll("_", " ")}</td><td>{service.billing_frequency === "included" ? "Included" : money(service.amount, service.currency)}</td><td>{service.active_subscriptions}</td><td><Badge tone={service.active ? "active" : "inactive"}>{service.active ? "active" : "inactive"}</Badge></td><td>{canConfigure && <OpenModalButton target={`service-edit-${service.id}`} icon="edit" className="text-button">Edit</OpenModalButton>}</td></tr>)}</tbody></table></div> : <Empty icon="services" title="No services configured" text={properties.length ? "Create module-relevant services and assign them to an active lease or individual resident." : "Enable a module with service plans and create a compatible property first."}/>}</section>

    <section className="panel module-section"><div className="panel-head"><div><span className="eyebrow">Active delivery</span><h2>Lease and resident subscriptions</h2></div>{services.some((service) => service.active) && leases.length ? <OpenModalButton target="service-assign" className="button secondary">Assign service</OpenModalButton> : null}</div>{subscriptions.length ? <div className="table-wrap"><table><thead><tr><th>Service</th><th>Lease / resident</th><th>Charge</th><th>Started</th><th>Current period</th><th>Status</th><th>Actions</th></tr></thead><tbody>{subscriptions.map((item) => {const amount=Number(item.custom_amount ?? item.service_amount);return <tr key={item.id}><td><strong>{item.service_name}</strong><small>{item.property_name} · {item.unit_name}</small></td><td>{item.lease_reference}<small>{item.tenant_name || "Lease-level service"}</small></td><td>{item.billing_frequency === "included" ? "Included" : money(amount,item.currency)}<small>{item.billing_frequency.replaceAll("_"," ")}</small></td><td>{dateLabel(item.start_date)}</td><td>{item.current_invoice_number ? <Badge tone="paid">{item.current_invoice_number}</Badge> : item.status === "active" && item.billing_frequency !== "included" ? <Badge tone="draft">Not billed</Badge> : <span className="quiet-copy">Not applicable</span>}</td><td><Badge tone={item.status}>{item.status}</Badge></td><td><div className="table-actions">{item.status === "active" && item.billing_frequency !== "included" && !item.current_invoice_id && <OpenModalButton target={`service-bill-${item.id}`} className="text-button">Bill</OpenModalButton>}{item.status === "active" && <form action={endServiceSubscriptionAction}><input type="hidden" name="subscriptionId" value={item.id}/><input type="hidden" name="endDate" value={today()}/><button className="text-button danger-text">End</button></form>}</div></td></tr>})}</tbody></table></div> : <Empty icon="services" title="No service subscriptions" text="Assign a catalogue service to an active lease or a specific linked resident."/>}</section>

    {canConfigure && properties.length > 0 && <form action={createServiceAction}><ModalForm id="service-create" title="Create a service" description="Configure the catalogue item before assigning it. Zero-value services cannot be invoiced separately." submitLabel="Create service"><div className="modal-body"><label><span>Property</span><select name="propertyId" required>{properties.map((property)=><option value={property.id} key={property.id}>{property.name}</option>)}</select></label><div className="field-grid two"><label><span>Service name</span><input name="name" required placeholder="Meal plan"/></label><label><span>Category</span><input name="category" placeholder="meals, laundry, CAM, parking"/></label></div><div className="field-grid two"><label><span>Billing frequency</span><select name="billingFrequency"><option value="included">Included</option><option value="one_time">One time</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option></select></label><label><span>Default charge</span><input type="number" min="0" step="0.01" name="amount" defaultValue="0"/></label></div><label><span>Description</span><textarea name="description" rows="3"/></label></div></ModalForm></form>}

    {canConfigure && services.map((service)=><form action={updateServiceAction} key={`edit-${service.id}`}><ModalForm id={`service-edit-${service.id}`} title={`Edit ${service.name}`} description="Existing subscriptions retain their custom charge; catalogue defaults affect future billing where no custom amount exists." submitLabel="Save service"><div className="modal-body"><input type="hidden" name="serviceId" value={service.id}/><div className="summary-box"><span>Property</span><strong>{service.property_name}</strong></div><div className="field-grid two"><label><span>Name</span><input name="name" defaultValue={service.name} required/></label><label><span>Category</span><input name="category" defaultValue={service.category}/></label></div><div className="field-grid two"><label><span>Frequency</span><select name="billingFrequency" defaultValue={service.billing_frequency}>{["included","one_time","monthly","quarterly","annual"].map((value)=><option value={value} key={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label><span>Default charge</span><input type="number" min="0" step="0.01" name="amount" defaultValue={service.amount}/></label></div><label><span>Description</span><textarea name="description" rows="3" defaultValue={service.description||""}/></label><label className="check-row"><input type="checkbox" name="active" defaultChecked={Boolean(service.active)}/><span><strong>Available for new assignments</strong><small>Deactivation does not erase existing subscriptions.</small></span></label></div></ModalForm></form>)}

    {services.some((service)=>service.active) && leases.length > 0 && <form action={subscribeServiceAction}><ModalForm id="service-assign" title="Assign a service" description="The server validates property, lease, and resident relationships and prevents duplicate active subscriptions." submitLabel="Assign service"><div className="modal-body"><label><span>Service</span><select name="serviceId" required>{services.filter((service)=>service.active).map((service)=><option value={service.id} key={service.id}>{service.property_name} · {service.name} · {service.billing_frequency.replaceAll("_"," ")}</option>)}</select></label><label><span>Active lease</span><select name="leaseId" required>{leases.map((lease)=><option value={lease.id} key={lease.id}>{lease.property_name} · {lease.unit_name} · {lease.reference}</option>)}</select></label><label><span>Specific resident (optional)</span><select name="tenantId"><option value="">Lease-level service</option>{tenants.map((tenant)=><option value={tenant.id} key={`${tenant.lease_id}-${tenant.id}`}>{tenant.full_name} · lease #{tenant.lease_id}</option>)}</select></label><div className="field-grid two"><label><span>Start date</span><input type="date" name="startDate" defaultValue={today()} required/></label><label><span>Custom charge (optional)</span><input type="number" min="0" step="0.01" name="customAmount" placeholder="Use catalogue default"/></label></div></div></ModalForm></form>}

    {subscriptions.filter((item)=>item.status==="active"&&item.billing_frequency!=="included"&&!item.current_invoice_id).map((item)=><form action={billServiceSubscriptionAction} key={`bill-${item.id}`}><ModalForm id={`service-bill-${item.id}`} title={`Bill ${item.service_name}`} description="The subscription and period pair is unique, so repeated submissions cannot create duplicate invoices." submitLabel="Create invoice"><div className="modal-body"><input type="hidden" name="subscriptionId" value={item.id}/><div className="summary-box"><span>Charge</span><strong>{money(Number(item.custom_amount??item.service_amount),item.currency)}</strong><small>{item.property_name} · {item.lease_reference} · {item.tenant_name||"lease level"}</small></div><label><span>Billing period</span><input name="period" defaultValue={period} readOnly={item.billing_frequency==="one_time"}/><small>{item.billing_frequency==="one_time"?"Stored as a one-time run.":"Use YYYY-MM."}</small></label><label><span>Invoice due date</span><input type="date" name="dueDate" defaultValue={today()} required/></label></div></ModalForm></form>)}
  </>;
}
